### ISSUE TITLE
Show comments in explorer view

### ISSUE THREAD

**Issue by Mattadore** [SanderRonde/VSCode-Gerrit#62]
Would it be possible to show review comments for the current change in the editor itself, rather than a separate view? 

I realize this may not be feasible, due to difficulties figuring out where to anchor the comment, but even showing the comment at the top of the page if the specific location can't be determined, like gerrit itself does, would be incredibly useful.

**Comment by SanderRonde** [comment]
That should already be the case if you've checked out a change. If you go to the gerrit tab, check out a change by clicking the down-arrow and then go to any file that contains a comment you should see it inline. Or is there another type of comments or situations that you mean?

**Comment by Mattadore** [comment]
If I open the "gerrit" tab I can see the files with their diffs and the comments inline, sure, but it's read-only and I can't edit it. I meant like, comments in the actual writable files, I can't see any comments in those even when I check it out directly. Is that supposed to work? What source is that info coming from, because git-review has been a bit inconsistent for me.

**Comment by SanderRonde** [comment]
You should see them. If you go to the gerrit panel you should see a little comment balloon behind files containing comments. Then in the diff view (clicking the file) you should indeed see the comments. Then if you check out that patch (by clicking the checkout icon) and then you navigate to the file you'll see any unresolved comments inline and resolved ones as expandable.

The source is the HTTP API for comments. `git-review` is only used for pushing patches.

**Comment by Mattadore** [comment]
It doesn't show up for me :(. The checkout name when I do that in git is "review/unknown/[change number]" and doing "next unresolved comment" gives me "Cannot read properties of null (reading '0')" if that helps at all. The "comments" tab is also empty when on the file. How would I debug this? I don't see any specific errors for it in the gerrit output. I can see it issuing valid requests to the correct address for that change in the output when I reload on the file, but no comments show up, with the comments tab saying "no comments in this workspace yet" :c

**Comment by SanderRonde** [comment]
The `review/unknown/[change number]` part sounds good, that's what gerrit does by default when you `git-review -d [change number]` on the command line. The `unknown` part is a bit weird though, it should contain the author name. Unless you have anonyous/unnamed users on your gerrit instance, just haven't personally seen that before.

I've now fixed the `Cannot read properties of null` issue, thanks for reporting that :)

I think maybe easiest to start debugging whether the comments are coming through at all. Do you see any comment balloons in the gerrit tab at all (for files where you'd expect them of course)? If not then it sounds like the comments aren't coming through. You said clicking the URLs leads to you a JSON file with no comments. Can you confirm that, for a change where you'd expect comments, the URL `{gerrit_host}/a/changes/{project}~{branch}~{changeID}/comments/` (you probably don't have to type it out and can find in the logs) returns a JSON file with no comments once visited in the browser? If so then somehow your gerrit instance is not exposing the comments to the web API for some reason.

**Comment by Mattadore** [comment]
Ahh, I think I miscommunicated, the json bundle is fine, I meant no comments show up on the file _in the editor_ despite it clearly making a valid web request for the comments. Additionally, the "gerrit" tab works great, it's just the file in the actual editor that lacks comments, or even a comment side bar.

**Comment by SanderRonde** [comment]
Thanks for looking into it! There's indeed a pretty big chance that that is the issue. I've fixed it in the below package, can you give that one a try? Note that those changes are based on top of the other file I sent you, maybe good to know.
[vscode--gerrit-1.2.34.zip](https://github.com/SanderRonde/VSCode-Gerrit/files/15210924/vscode--gerrit-1.2.34.zip)

**Comment by Mattadore** [comment]
It doesn't fix the issue but it helps, it's.. very weird.  So, opening the file normally does not show comments or even the comment gutter. However, not only does the side-by-side view show comments, it now lets me edit the file! I can also press the "open file" button to open the file by itself, and that lets me edit and shows comments, but it's missing error highlighting (but not semantic autocomplete??)

What I think is going on, is that when I open the file normally it shows like `subfolder/filename.cpp` and when I open in the gerrit view, it's the full path `/home/me/reponame/subfolder/filename.cpp` and it's treating those as separate files. It seems like there is an issue with using the full path, and vscode just wants the path from the workspace root. But the path is correct now at least! It's just that vscode wants a relative path from the workspace root, not an absolute path, to recognize the file as the same.

**Comment by SanderRonde** [comment]
Ah yeah that's a bit of a running issue that is separate from your case. I'll merge the fix and try to solve that issue after. Thanks for testing!

**Comment by SanderRonde** [comment]
I'm pretty sure I've fixed the issue, including making comments work for the opening-the-file-normally case. I'll be publishing these changes in version `1.1.36` so let me know if it works. I'll just close the issue for now, but feel free to re-open if it turns out something doesn't work.
